spring:
  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.mailgun.org
    username: chirp@sandbox93a010470e2b4276bbf00e4c3b7953ba.mailgun.org

jwt:
  expiration-minutes: 1000

nginx:
  require-proxy: false

chirp:
  email:
    url: "http://localhost:8080"
  rate-limit:
    ip:
      apply-limit: false
  web-socket:
    allowed-origin: "http://localhost:8080"
